notifications:
  email:
    recipients:
      - guillaumemarcoux@gmail.com
    on_failure: change

language: node_js

install:
  - pip install --user html5validator
  - npm install jshint

script:
  - html5validator --log INFO --blacklist node_modules
  - jshint ./